apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: predlogi
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - predlogi.cinecore.timhrovat.com
    secretName: predlogi-tls
  rules:
  - host: predlogi.cinecore.timhrovat.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: predlogi
            port:
              number: 8080
